name: openMINDS_OWL_build_pipeline

on:
  push:
    branches:
      - pipeline
  workflow_dispatch: # This triggers the workflow when a webhook is received

jobs:
    build:
      runs-on: ubuntu-latest
      steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Run build
        run: |
          uv pip install --system -r requirements.txt
          python build.py

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to main
        run: |
          cp -R target/* main
          cd main       
          git config --global user.email "support@openmetadatainitiative.org"
          git config --global user.name "openMINDS pipeline"
          if [[ $(git add . --dry-run | wc -l) -gt 0 ]]; then
              git add .
              git commit -m "build triggered by ${{ github.event_name }}"
              git push -f
          else
              echo "Nothing to commit"
          fi
